permalink: /:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "pages.html"]
auto: true
pygments: true
title : InfoSecly
tagline: Everything on Information Security
author :
  name : Infosecly.com
  email : infosecly@gmail.com
  github : abcom
  twitter : infosecly
  feedburner : infosecly

production_url : http://infosecly.com

JB :
  version : 0.3.0

  BASE_PATH : false

  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : infosecly
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-41003488-1'
  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
